### ISSUE TITLE
とりあえずの課題

### ISSUE THREAD

**Issue by Kamidama** [Arfikait-Sirius/StartStory#1]

**Comment by Kamidama** [comment]
* 物語のテーマ

**Comment by Arfikait-Sirius** [comment]
# ジャンル
* SF
  * 異世界
    * スチーム
  * 超能力
    * 魔法
      * 大古の文明
    * 科学
      * 最新技術
    * 第六感
      * 身体能力進化
  * サイバー
  * ~~スペース~~
  * ~~バイオ~~
  * ~~タイムリープ~~
* 恋愛
* ~~スポコン~~
* ミステリー
* ~~日常~~
* ~~ノスタルジー~~

**Comment by Arfikait-Sirius** [comment]
# エンド

## トゥルー
* 宝を得る
* 仲間に巡り合う
* 親しい人の不幸が幸福に転じる

## ノーマル
* これからも同じなのだろう
* 現状維持

## バッド
* **主人公は生存**
  * 親族が不幸
* 孤独
  * 恋人と結ばれない
* 世界滅亡
  * 魔王に支配される
* 破産
* 無職
* 財産を失う

**Comment by Arfikait-Sirius** [comment]
# スタート
* ある程度は財産がある状態
  * 失いたくないものがある
  * 仲間
  * 親族
  * 能力
  * 金
* いきなり窮地開始

**Comment by Arfikait-Sirius** [comment]
# ストーリー進行

## 最高潮

### 回数
* 2回

### 内容
* プラスの出来事
* 直後にマイナスの出来事につながる選択肢

## エンド分岐

* プラス -> プラス -> プラス
  * ノーマル
* プラス -> マイナス -> プラス
  * トゥルー
* それ以外
  * バッド

**Comment by Arfikait-Sirius** [comment]
# ストーリー内容

## 概要

1. 主人公は守銭奴でなかなかのクズ
1. 宝を求めて遺跡へ冒険に行く
1. 宝を一旦見つける
1. なんやかんやあって最初に持っているものも全て失う
1. 仲間が助けてくれる
1. 主人公気付く
1. 本当の宝は仲間だったんだ 

## キャラクター

### 主人公
* 守銭奴でクズ
* 仲間も同じように宝を獲りに来たと思い込む
  * 仲間の財布を盗む
* 仲間が幼少期にくれた宝を唯一身に着けている
  * 仲間のなにかしらの言動で裏切られたと感じてクズの一途を辿る

### 仲間
* 遺跡の研究家
* 実は主人公の唯一の仲良しだった幼馴染
  * 主人公のことを出会ったときは覚えていない
